### ISSUE TITLE
Public access block policies cannot be created if already blocked at account level

### ISSUE THREAD

**Issue by littlebigfab** [trussworks/terraform-aws-bootstrap#51]
Hello,

The call to the `terraform-aws-s3-private-bucket` fails (Access Denied status code: 403) if public access to S3 buckets is already blocked at account level.

In AWS Console:
<img width="789" alt="121037624-2c9daf80-c7e2-11eb-8611-1a8235d9d2f5" src="https://user-images.githubusercontent.com/49759900/123822864-3d4bcc00-d92f-11eb-816a-d909c28f1c40.png">

The problem has been fixed in `terraform-aws-s3-private-bucket` version `3.6.0`. Please refer to: https://github.com/trussworks/terraform-aws-s3-private-bucket/issues/252

Is it possible to propagate the new variable `enable_s3_public_access_block` to the present module (`terraform-aws-bootstrap`) as well?

**Comment by dynamike** [comment]
yup, we'll have a PR up soonish.

**Comment by CoryAtTruss** [comment]
This issue is resolved in the 1.5.0 release. Thank you for your report!
